# Generated by Django 5.1.3 on 2025-03-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureResourceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceFormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceFormFieldsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AzureResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('imageURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceFormFieldsOptionsRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('azureresourceformfields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfields')),
                ('azureresourceformfieldsoptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfieldsoptions')),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceFormFieldsRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('azureresourceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceform')),
                ('azureresourceformfields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfields')),
            ],
        ),
        migrations.AddField(
            model_name='azureresourceform',
            name='azureresource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresources'),
        ),
    ]
