# Generated by Django 5.1.3 on 2025-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureresourceformfields',
            name='type',
            field=models.CharField(choices=[('sel', 'Select'), ('txt', 'Text')], default='txt', max_length=3),
        ),
    ]
