# Generated by Django 5.1.3 on 2025-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0002_azureresourceformfields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourceformfields',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text')], default='txt', max_length=10),
        ),
    ]
