# Generated by Django 5.1.3 on 2025-03-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0003_alter_azureresourceformfields_type'),
    ]

    operations = [
    ]
