# Generated by Django 5.1.3 on 2025-03-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0004_update_field_type_choices'),
    ]

    operations = [
    ]
