# Generated by Django 5.1.7 on 2025-03-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0006_alter_azureresourceform_azureresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourceform',
            name='azureresource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresources'),
        ),
    ]
