# Generated by Django 5.1.7 on 2025-03-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0007_alter_azureresourceform_azureresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureResourceCreationFormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('select', 'Select'), ('text', 'Text')], default='txt', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceCreationFormFieldsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceCreationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('azureresource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresources')),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceCreationFormFieldsOptionsRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('azureresourceformfields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfields')),
                ('azureresourceformfieldsoptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfieldsoptions')),
            ],
        ),
        migrations.CreateModel(
            name='AzureResourceCreationFormFieldsRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('azureresourceform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceform')),
                ('azureresourceformfields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourceformfields')),
            ],
        ),
    ]
