# Generated by Django 5.1.7 on 2025-03-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0008_azureresourcecreationformfields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourcecreationformfieldsoptionsrel',
            name='azureresourceformfields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourcecreationformfields'),
        ),
        migrations.AlterField(
            model_name='azureresourcecreationformfieldsoptionsrel',
            name='azureresourceformfieldsoptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourcecreationformfieldsoptions'),
        ),
        migrations.AlterField(
            model_name='azureresourcecreationformfieldsrel',
            name='azureresourceform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourcecreationform'),
        ),
        migrations.AlterField(
            model_name='azureresourcecreationformfieldsrel',
            name='azureresourceformfields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlforms.azureresourcecreationformfields'),
        ),
    ]
