# Generated by Django 5.1.7 on 2025-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0009_alter_azureresourcecreationformfieldsoptionsrel_azureresourceformfields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azureresourcecreationformfieldsrel',
            name='azureresourceform',
        ),
        migrations.RemoveField(
            model_name='azureresourcecreationformfieldsrel',
            name='azureresourceformfields',
        ),
        migrations.AddField(
            model_name='azureresourcecreationform',
            name='formfields',
            field=models.ManyToManyField(blank=True, to='atlforms.azureresourceformfields'),
        ),
        migrations.AddField(
            model_name='azureresourcecreationformfields',
            name='options',
            field=models.ManyToManyField(blank=True, to='atlforms.azureresourceformfieldsoptions'),
        ),
        migrations.DeleteModel(
            name='AzureResourceCreationFormFieldsOptionsRel',
        ),
        migrations.DeleteModel(
            name='AzureResourceCreationFormFieldsRel',
        ),
    ]
