# Generated by Django 5.1.7 on 2025-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0010_remove_azureresourcecreationformfieldsrel_azureresourceform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourcecreationform',
            name='formfields',
            field=models.ManyToManyField(blank=True, to='atlforms.azureresourcecreationformfields'),
        ),
        migrations.AlterField(
            model_name='azureresourcecreationformfields',
            name='options',
            field=models.ManyToManyField(blank=True, to='atlforms.azureresourcecreationformfieldsoptions'),
        ),
    ]
