# Generated by Django 5.1.7 on 2025-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0011_alter_azureresourcecreationform_formfields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureresourceformfields',
            name='helper_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='azureresourceformfields',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
