# Generated by Django 5.1.7 on 2025-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0012_azureresourceformfields_helper_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourceformfields',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('checkbox', 'Checkbox')], default='txt', max_length=10),
        ),
    ]
