# Generated by Django 5.1.7 on 2025-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlforms', '0013_alter_azureresourceformfields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureresourcecreationformfields',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('checkbox', 'Checkbox')], default='txt', max_length=10),
        ),
    ]
